input_features:
    -
        name: name
        type: text
    -
        name: year
        type: numerical

output_features:
    -
        name: location
        type: category

training:
    training_set_metadata_file_path: training_set_metadata.json
    training_set_file_path: training_data.training.hdf5
    validation_set_file_path: training_data.validation.hdf5
    test_set_file_path: training_data.test.hdf5
