name: Flask App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up environment variable
      run: |
        echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest
  deploy:
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
          command: |
            doctl auth init -t "${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}"
            doctl compute ssh-key import my-key --public-key-file=$HOME/.ssh/id_rsa.pub
            doctl compute ssh-key list
            doctl compute droplet list
            doctl compute droplet ssh ${{ secrets.SERVER_IP }} --ssh-command="git clone https://github.com/noveoko/24nme.github.io.git && cd 24nme.github.io && gunicorn main:app -b 0.0.0.0:80"    
      - name: Verify app availability
        run: |
          set -e
          if ! curl -Is https://24n.me | head -n 1 | grep "HTTP/1.[01] [23].."; then
            echo "Error: App is not available"
            exit 1
          fi
