name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        environment: ["digital ocean"]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        environment: ${{ matrix.environment }}

    - name: Create virtual environment
      run: python -m venv myenv

    - name: Activate virtual environment
      run: |
        source myenv/bin/activate

    - name: Assign secret key
      run: export FLASK_SECRET_KEY="${{ secrets.FLASK_SECRET_KEY }}"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
