name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

    - name: Install dependencies
      run: pip install pytest flask gunicorn

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

      - name: Test app
        run: |
          . venv/bin/activate
          pytest tests/test_app.py

      - name: Deploy app
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          source: "."
          target: "/root/24nme.github.io"
