name: Flask App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up environment variable
      run: |
        echo "FLASK_SECRET_KEY=${{ env.FLASK_SECRET_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest


  deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup SSH
          uses: webfactory/ssh-agent@v0.5.0
          with:
            ssh-private-key: ${{ env.SSH_PUBLIC_KEY }}

        - name: Reset Droplet
          run: ssh worker@{{ env.SERVER_IP }} 'sudo systemctl restart your-flask-app.service'

        - name: Install dependencies
          run: ssh worker@{{ env.SERVER_IP }}  'sudo apt-get update && sudo apt-get install -y python3-pip python3-venv && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt'

        - name: Start Flask app
          run: ssh worker@{{ env.SERVER_IP }}  'source venv/bin/activate && nohup python3 app.py &'
