name: Deploy FastAPI app

on:
  push:
    branches: [main]

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SERVER_IP: <your server IP>

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx python3-pip
          sudo pip3 install fastapi uvicorn

      - name: Build and start app
        run: |
          sudo systemctl stop fastapi.service || true
          sudo systemctl disable fastapi.service || true
          sudo rm -f /etc/systemd/system/fastapi.service
          sudo touch /etc/systemd/system/fastapi.service
          sudo chmod 664 /etc/systemd/system/fastapi.service

          echo "[Unit]
          Description=FastAPI App
          After=network.target

          [Service]
          User=$SSH_USERNAME
          WorkingDirectory=$GITHUB_WORKSPACE
          ExecStart=/usr/local/bin/uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80
          Restart=always

          [Install]
          WantedBy=multi-user.target" | sudo tee /etc/systemd/system/fastapi.service >/dev/null

          sudo systemctl daemon-reload
          sudo systemctl enable fastapi.service
          sudo systemctl restart fastapi.service
